### ISSUE TITLE
Standardized journal for real-life uses of algorithms.

### ISSUE THREAD

**Issue by adeepak7** [vsoch/algorithms#15]
@vsoch - While having a look at your profile, I came across this repo. I am a big fan of competitive programming and algorithms, with an overall experience of 6 years.

I also did crack the Codechef Certified Advanced Data Structure and Algorithm Programme - Advanced Level examination.

But, throughout my journey, I realized the fact that how frequently we use these algorithms in real life. We use them indirectly, but we are aware of them.

Therefore, I think there is a need for a journal that will possess the applications of the particular algorithm. Humans remember the things that they usually do or feel. Contemplating on applications will help them to visualize and feel the things going around them.

Looking forward to your thoughts.

**Comment by vsoch** [comment]
This was just for fun, I rarely use this kind of thing in any real world practice.

What actionable item does this issue suggest?

**Comment by adeepak7** [comment]
This suggests that there should be a repo/journal with standard contributing guidelines to maintain real-life uses/applications of all algorithms at one single place.

**Comment by vsoch** [comment]
That's a great idea @adeepak7! I think the closest to what you might be looking for is [geeks to geeks](https://www.geeksforgeeks.org/fundamentals-of-algorithms/#AnalysisofAlgorithms) - it has both lessons, examples, and user contributions. To be clear, this repository is for my personal enjoyment and practice - I don't claim anything here is optimal or complete, and I do work on behalf of my research community, and there is no current need for this kind of resource because there are ample out there. Other resources you might find helpful:

 - [Exercism](https://exercism.io/my/tracks/python) 
 - [Project Euler](https://projecteuler.net/)
 - [algorithm courses](https://www.freecodecamp.org/news/these-are-the-best-free-courses-to-learn-data-structures-and-algorithms-in-depth-4d52f0d6b35a/)

The above can offer community around such a topic. And per your suggestion, there are actually [algorithm journals](https://www.mdpi.com/journal/algorithms).
